version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "06:00"
      timezone: "Australia/Melbourne"
    labels:
      - "automerge"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "06:00"
      timezone: "Australia/Melbourne"
    labels:
      - "automerge"
    groups:
      all:
        patterns:
          - "*"
