// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: buckets.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createBucket = `-- name: CreateBucket :one
INSERT INTO float.buckets (user_id, name)
VALUES ($1, $2)
RETURNING bucket_id, user_id, name, is_general, created_at
`

func (q *Queries) CreateBucket(ctx context.Context, userID uuid.UUID, name string) (FloatBucket, error) {
	row := q.db.QueryRowContext(ctx, createBucket, userID, name)
	var i FloatBucket
	err := row.Scan(
		&i.BucketID,
		&i.UserID,
		&i.Name,
		&i.IsGeneral,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBucket = `-- name: DeleteBucket :exec
DELETE FROM float.buckets
WHERE bucket_id = $1 AND user_id = $2
`

func (q *Queries) DeleteBucket(ctx context.Context, bucketID uuid.UUID, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteBucket, bucketID, userID)
	return err
}

const ensureGeneralBucket = `-- name: EnsureGeneralBucket :exec
INSERT INTO float.buckets (user_id, name, is_general)
VALUES ($1, 'General', TRUE)
ON CONFLICT (user_id, name) DO UPDATE SET is_general = TRUE
`

func (q *Queries) EnsureGeneralBucket(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, ensureGeneralBucket, userID)
	return err
}

const getBucket = `-- name: GetBucket :one
SELECT b.bucket_id, b.user_id, b.name, b.is_general, b.created_at, COALESCE(SUM(l.amount_cents), 0)::BIGINT AS balance_cents
FROM float.buckets b
LEFT JOIN float.bucket_ledger l ON b.bucket_id = l.bucket_id
WHERE b.bucket_id = $1 AND b.user_id = $2
GROUP BY b.bucket_id
`

type GetBucketRow struct {
	BucketID     uuid.UUID
	UserID       uuid.UUID
	Name         string
	IsGeneral    bool
	CreatedAt    time.Time
	BalanceCents int64
}

func (q *Queries) GetBucket(ctx context.Context, bucketID uuid.UUID, userID uuid.UUID) (GetBucketRow, error) {
	row := q.db.QueryRowContext(ctx, getBucket, bucketID, userID)
	var i GetBucketRow
	err := row.Scan(
		&i.BucketID,
		&i.UserID,
		&i.Name,
		&i.IsGeneral,
		&i.CreatedAt,
		&i.BalanceCents,
	)
	return i, err
}

const getGeneralBucket = `-- name: GetGeneralBucket :one
SELECT bucket_id, user_id, name, is_general, created_at FROM float.buckets WHERE user_id = $1 AND is_general = TRUE
`

func (q *Queries) GetGeneralBucket(ctx context.Context, userID uuid.UUID) (FloatBucket, error) {
	row := q.db.QueryRowContext(ctx, getGeneralBucket, userID)
	var i FloatBucket
	err := row.Scan(
		&i.BucketID,
		&i.UserID,
		&i.Name,
		&i.IsGeneral,
		&i.CreatedAt,
	)
	return i, err
}

const listBuckets = `-- name: ListBuckets :many
SELECT b.bucket_id, b.user_id, b.name, b.is_general, b.created_at, b.display_order, COALESCE(SUM(l.amount_cents), 0)::BIGINT AS balance_cents
FROM float.buckets b
LEFT JOIN float.bucket_ledger l ON b.bucket_id = l.bucket_id
WHERE b.user_id = $1
GROUP BY b.bucket_id
ORDER BY b.display_order NULLS LAST, b.created_at ASC
`

type ListBucketsRow struct {
	BucketID     uuid.UUID
	UserID       uuid.UUID
	Name         string
	IsGeneral    bool
	CreatedAt    time.Time
	DisplayOrder sql.NullInt32
	BalanceCents int64
}

func (q *Queries) ListBuckets(ctx context.Context, userID uuid.UUID) ([]ListBucketsRow, error) {
	rows, err := q.db.QueryContext(ctx, listBuckets, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBucketsRow
	for rows.Next() {
		var i ListBucketsRow
		if err := rows.Scan(
			&i.BucketID,
			&i.UserID,
			&i.Name,
			&i.IsGeneral,
			&i.CreatedAt,
			&i.DisplayOrder,
			&i.BalanceCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBucketDisplayOrder = `-- name: SetBucketDisplayOrder :exec
UPDATE float.buckets
SET display_order = $2
WHERE bucket_id = $1 AND user_id = $3
`

func (q *Queries) SetBucketDisplayOrder(ctx context.Context, bucketID uuid.UUID, displayOrder int32, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, setBucketDisplayOrder, bucketID, displayOrder, userID)
	return err
}

const reassignBucketTransactionsToGeneral = `-- name: ReassignBucketTransactionsToGeneral :exec
UPDATE float.up_transactions t
SET bucket_id = (SELECT b2.bucket_id FROM float.buckets b1 JOIN float.buckets b2 ON b1.user_id = b2.user_id AND b2.is_general = TRUE WHERE b1.bucket_id = $1)
WHERE t.bucket_id = $1
`

func (q *Queries) ReassignBucketTransactionsToGeneral(ctx context.Context, bucketID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, reassignBucketTransactionsToGeneral, bucketID)
	return err
}
