// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: classification_log.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const insertClassificationLog = `-- name: InsertClassificationLog :exec
INSERT INTO float.classification_log (transaction_id, chosen_bucket_id, confidence, reasoning, model)
VALUES ($1, $2, $3, $4, $5)
`

type InsertClassificationLogParams struct {
	TransactionID  uuid.UUID
	ChosenBucketID uuid.UUID
	Confidence     float32
	Reasoning      string
	Model          string
}

func (q *Queries) InsertClassificationLog(ctx context.Context, arg InsertClassificationLogParams) error {
	_, err := q.db.ExecContext(ctx, insertClassificationLog,
		arg.TransactionID,
		arg.ChosenBucketID,
		arg.Confidence,
		arg.Reasoning,
		arg.Model,
	)
	return err
}
