// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: covers.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createCover = `-- name: CreateCover :one
INSERT INTO float.bucket_transfers (from_bucket_id, to_bucket_id, amount_cents, note, covers_transaction_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING transfer_id, from_bucket_id, to_bucket_id, amount_cents, note, created_at, covers_transaction_id
`

type CreateCoverParams struct {
	FromBucketID        uuid.UUID
	ToBucketID          uuid.UUID
	AmountCents         int64
	Note                string
	CoversTransactionID uuid.NullUUID
}

func (q *Queries) CreateCover(ctx context.Context, arg CreateCoverParams) (FloatBucketTransfer, error) {
	row := q.db.QueryRowContext(ctx, createCover,
		arg.FromBucketID,
		arg.ToBucketID,
		arg.AmountCents,
		arg.Note,
		arg.CoversTransactionID,
	)
	var i FloatBucketTransfer
	err := row.Scan(
		&i.TransferID,
		&i.FromBucketID,
		&i.ToBucketID,
		&i.AmountCents,
		&i.Note,
		&i.CreatedAt,
		&i.CoversTransactionID,
	)
	return i, err
}

const deleteCover = `-- name: DeleteCover :execrows
DELETE FROM float.bucket_transfers t
USING float.up_transactions tx
JOIN float.buckets b ON tx.bucket_id = b.bucket_id
WHERE t.covers_transaction_id = tx.transaction_id
  AND t.transfer_id = $1
  AND b.user_id = $2
`

func (q *Queries) DeleteCover(ctx context.Context, transferID uuid.UUID, userID uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCover, transferID, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getTransactionOwner = `-- name: GetTransactionOwner :one
SELECT tx.transaction_id, tx.bucket_id, tx.amount_cents, b.user_id
FROM float.up_transactions tx
JOIN float.buckets b ON tx.bucket_id = b.bucket_id
WHERE tx.transaction_id = $1 AND b.user_id = $2
`

type GetTransactionOwnerRow struct {
	TransactionID uuid.UUID
	BucketID      uuid.UUID
	AmountCents   int64
	UserID        uuid.UUID
}

func (q *Queries) GetTransactionOwner(ctx context.Context, transactionID uuid.UUID, userID uuid.UUID) (GetTransactionOwnerRow, error) {
	row := q.db.QueryRowContext(ctx, getTransactionOwner, transactionID, userID)
	var i GetTransactionOwnerRow
	err := row.Scan(
		&i.TransactionID,
		&i.BucketID,
		&i.AmountCents,
		&i.UserID,
	)
	return i, err
}

const listCoversByBucket = `-- name: ListCoversByBucket :many
SELECT t.transfer_id, t.amount_cents, t.note, t.created_at, t.covers_transaction_id,
       tx.description AS transaction_description
FROM float.bucket_transfers t
JOIN float.up_transactions tx ON t.covers_transaction_id = tx.transaction_id
WHERE tx.bucket_id = $1
`

type ListCoversByBucketRow struct {
	TransferID             uuid.UUID
	AmountCents            int64
	Note                   string
	CreatedAt              time.Time
	CoversTransactionID    uuid.NullUUID
	TransactionDescription string
}

func (q *Queries) ListCoversByBucket(ctx context.Context, bucketID uuid.UUID) ([]ListCoversByBucketRow, error) {
	rows, err := q.db.QueryContext(ctx, listCoversByBucket, bucketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCoversByBucketRow
	for rows.Next() {
		var i ListCoversByBucketRow
		if err := rows.Scan(
			&i.TransferID,
			&i.AmountCents,
			&i.Note,
			&i.CreatedAt,
			&i.CoversTransactionID,
			&i.TransactionDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoversByTransaction = `-- name: ListCoversByTransaction :many
SELECT transfer_id, amount_cents, note, created_at, covers_transaction_id
FROM float.bucket_transfers
WHERE covers_transaction_id = $1
`

type ListCoversByTransactionRow struct {
	TransferID          uuid.UUID
	AmountCents         int64
	Note                string
	CreatedAt           time.Time
	CoversTransactionID uuid.NullUUID
}

func (q *Queries) ListCoversByTransaction(ctx context.Context, coversTransactionID uuid.NullUUID) ([]ListCoversByTransactionRow, error) {
	rows, err := q.db.QueryContext(ctx, listCoversByTransaction, coversTransactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCoversByTransactionRow
	for rows.Next() {
		var i ListCoversByTransactionRow
		if err := rows.Scan(
			&i.TransferID,
			&i.AmountCents,
			&i.Note,
			&i.CreatedAt,
			&i.CoversTransactionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
