// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: fx_rates.sql

package database

import (
	"context"
	"time"
)

const getFXRate = `-- name: GetFXRate :one
SELECT rate FROM float.fx_rates
WHERE base_currency = $1 AND quote_currency = $2 AND date = $3::DATE
`

func (q *Queries) GetFXRate(ctx context.Context, baseCurrency string, quoteCurrency string, column3 time.Time) (float64, error) {
	row := q.db.QueryRowContext(ctx, getFXRate, baseCurrency, quoteCurrency, column3)
	var rate float64
	err := row.Scan(&rate)
	return rate, err
}

const upsertFXRate = `-- name: UpsertFXRate :exec
INSERT INTO float.fx_rates (base_currency, quote_currency, rate, date)
VALUES ($1, $2, $3, $4)
ON CONFLICT (base_currency, quote_currency, date) DO UPDATE SET rate = EXCLUDED.rate
`

type UpsertFXRateParams struct {
	BaseCurrency  string
	QuoteCurrency string
	Rate          float64
	Date          time.Time
}

func (q *Queries) UpsertFXRate(ctx context.Context, arg UpsertFXRateParams) error {
	_, err := q.db.ExecContext(ctx, upsertFXRate,
		arg.BaseCurrency,
		arg.QuoteCurrency,
		arg.Rate,
		arg.Date,
	)
	return err
}
