// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: health_notifications.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getBucketHealthNotification = `-- name: GetBucketHealthNotification :one
SELECT health_notified_at FROM float.buckets
WHERE bucket_id = $1 AND user_id = $2
`

func (q *Queries) GetBucketHealthNotification(ctx context.Context, bucketID uuid.UUID, userID uuid.UUID) (sql.NullTime, error) {
	row := q.db.QueryRowContext(ctx, getBucketHealthNotification, bucketID, userID)
	var health_notified_at sql.NullTime
	err := row.Scan(&health_notified_at)
	return health_notified_at, err
}

const setBucketHealthNotifiedAt = `-- name: SetBucketHealthNotifiedAt :exec
UPDATE float.buckets SET health_notified_at = now()
WHERE bucket_id = $1 AND user_id = $2
`

func (q *Queries) SetBucketHealthNotifiedAt(ctx context.Context, bucketID uuid.UUID, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, setBucketHealthNotifiedAt, bucketID, userID)
	return err
}
