// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: health_notifications.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getBucketHealthNotification = `-- name: GetBucketHealthNotification :one
SELECT notified_at FROM float.bucket_health_notifications
WHERE bucket_id = $1 AND user_id = $2
`

func (q *Queries) GetBucketHealthNotification(ctx context.Context, bucketID uuid.UUID, userID uuid.UUID) (time.Time, error) {
	row := q.db.QueryRowContext(ctx, getBucketHealthNotification, bucketID, userID)
	var notified_at time.Time
	err := row.Scan(&notified_at)
	return notified_at, err
}

const upsertBucketHealthNotification = `-- name: UpsertBucketHealthNotification :exec
INSERT INTO float.bucket_health_notifications (bucket_id, user_id, notified_at)
VALUES ($1, $2, now())
ON CONFLICT (bucket_id, user_id) DO UPDATE SET notified_at = now()
`

func (q *Queries) UpsertBucketHealthNotification(ctx context.Context, bucketID uuid.UUID, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, upsertBucketHealthNotification, bucketID, userID)
	return err
}
