// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type FloatBucket struct {
	BucketID  uuid.UUID
	UserID    uuid.UUID
	Name      string
	IsGeneral bool
	CreatedAt time.Time
}

type FloatBucketLedger struct {
	BucketID      uuid.UUID
	AmountCents   int64
	CreatedAt     time.Time
	IsTransaction bool
	TransactionID uuid.UUID
}

type FloatBucketTransfer struct {
	TransferID   uuid.UUID
	FromBucketID uuid.UUID
	ToBucketID   uuid.UUID
	AmountCents  int64
	Note         string
	CreatedAt    time.Time
}

type FloatFcmToken struct {
	UserID   uuid.UUID
	FcmToken string
}

type FloatUpTransaction struct {
	TransactionID   uuid.UUID
	BucketID        uuid.UUID
	Description     string
	Message         string
	AmountCents     int64
	DisplayAmount   string
	CurrencyCode    string
	CreatedAt       time.Time
	TransactionType sql.NullString
	DeepLinkUrl     string
	RawJson         json.RawMessage
}

type FloatUser struct {
	UserID    uuid.UUID
	Email     string
	CreatedAt time.Time
}

type FloatUserToken struct {
	UserID  uuid.UUID
	UpToken string
}
