// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type FloatBucket struct {
	BucketID     uuid.UUID
	UserID       uuid.UUID
	Name         string
	IsGeneral    bool
	CreatedAt    time.Time
	DisplayOrder sql.NullInt32
	CurrencyCode sql.NullString
}

type FloatBucketLedger struct {
	TransactionID       uuid.UUID
	BucketID            uuid.UUID
	Description         string
	Message             string
	AmountCents         int64
	ForeignCurrencyCode sql.NullString
	ForeignAmountCents  sql.NullInt64
	CreatedAt           time.Time
	IsTransaction       bool
}

type FloatBucketTransfer struct {
	TransferID   uuid.UUID
	FromBucketID uuid.UUID
	ToBucketID   uuid.UUID
	AmountCents  int64
	Note         string
	CreatedAt    time.Time
}

type FloatBucketTrickle struct {
	TrickleID    uuid.UUID
	FromBucketID uuid.UUID
	ToBucketID   uuid.UUID
	AmountCents  int64
	Description  string
	Period       string
	StartDate    time.Time
	EndDate      sql.NullTime
	CreatedAt    time.Time
}

type FloatFcmToken struct {
	UserID   uuid.UUID
	FcmToken string
}

type FloatFxRate struct {
	BaseCurrency  string
	QuoteCurrency string
	Rate          float64
	Date          time.Time
}

type FloatRule struct {
	RuleID              uuid.UUID
	BucketID            uuid.UUID
	Name                string
	Priority            int32
	DescriptionContains sql.NullString
	MinAmountCents      sql.NullInt64
	MaxAmountCents      sql.NullInt64
	TransactionType     sql.NullString
	CategoryID          sql.NullString
	DateFrom            sql.NullTime
	DateTo              sql.NullTime
	ForeignCurrencyCode sql.NullString
	CreatedAt           time.Time
}

type FloatUpTransaction struct {
	TransactionID       uuid.UUID
	BucketID            uuid.UUID
	Description         string
	Message             string
	AmountCents         int64
	CreatedAt           time.Time
	TransactionType     sql.NullString
	RawJson             json.RawMessage
	CategoryID          sql.NullString
	ForeignCurrencyCode sql.NullString
	ForeignAmountCents  sql.NullInt64
}

type FloatUser struct {
	UserID        uuid.UUID
	Email         string
	CreatedAt     time.Time
	UpToken       sql.NullString
	WebhookSecret sql.NullString
}
