// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: push.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getUserFCMTokens = `-- name: GetUserFCMTokens :many
SELECT fcm_token FROM float.fcm_tokens
WHERE user_id = $1
`

func (q *Queries) GetUserFCMTokens(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getUserFCMTokens, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var fcm_token string
		if err := rows.Scan(&fcm_token); err != nil {
			return nil, err
		}
		items = append(items, fcm_token)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerFCMToken = `-- name: RegisterFCMToken :exec
WITH deleted AS (
    DELETE FROM float.fcm_tokens WHERE user_id = $1
)
INSERT INTO float.fcm_tokens (user_id, fcm_token) VALUES ($1, $2)
ON CONFLICT (fcm_token) DO UPDATE SET user_id = EXCLUDED.user_id
`

func (q *Queries) RegisterFCMToken(ctx context.Context, userID uuid.UUID, fcmToken string) error {
	_, err := q.db.ExecContext(ctx, registerFCMToken, userID, fcmToken)
	return err
}

const unregisterFCMToken = `-- name: UnregisterFCMToken :exec
DELETE FROM float.fcm_tokens
WHERE user_id = $1 AND fcm_token = $2
`

func (q *Queries) UnregisterFCMToken(ctx context.Context, userID uuid.UUID, fcmToken string) error {
	_, err := q.db.ExecContext(ctx, unregisterFCMToken, userID, fcmToken)
	return err
}
