// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	AssignTransactionToBucket(ctx context.Context, transactionID uuid.UUID, bucketID uuid.UUID) error
	CreateBucket(ctx context.Context, userID uuid.UUID, name string) (FloatBucket, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (FloatBucketTransfer, error)
	DeleteBucket(ctx context.Context, bucketID uuid.UUID, userID uuid.UUID) error
	DeleteTransfer(ctx context.Context, transferID uuid.UUID, userID uuid.UUID) (int64, error)
	DeleteUpTransaction(ctx context.Context, transactionID uuid.UUID) error
	EnsureGeneralBucket(ctx context.Context, userID uuid.UUID) error
	GetBucket(ctx context.Context, bucketID uuid.UUID, userID uuid.UUID) (GetBucketRow, error)
	GetTransaction(ctx context.Context, transactionID uuid.UUID, userID uuid.UUID) (FloatBucketLedger, error)
	GetUserByEmail(ctx context.Context, email string) (FloatUser, error)
	GetUserByID(ctx context.Context, userID uuid.UUID) (FloatUser, error)
	GetUserFCMTokens(ctx context.Context, userID uuid.UUID) ([]string, error)
	GetUserToken(ctx context.Context, userID uuid.UUID) (sql.NullString, error)
	GetUserWebhookSecret(ctx context.Context, userID uuid.UUID) (sql.NullString, error)
	ListBucketTransactions(ctx context.Context, bucketID uuid.UUID) ([]FloatBucketLedger, error)
	ListBuckets(ctx context.Context, userID uuid.UUID) ([]ListBucketsRow, error)
	ListTransactions(ctx context.Context, userID uuid.UUID) ([]FloatBucketLedger, error)
	ListTransfers(ctx context.Context, userID uuid.UUID) ([]ListTransfersRow, error)
	ReassignBucketTransactionsToGeneral(ctx context.Context, bucketID uuid.UUID) error
	RegisterFCMToken(ctx context.Context, userID uuid.UUID, fcmToken string) error
	SetUserToken(ctx context.Context, userID uuid.UUID, upToken sql.NullString) error
	SetUserWebhookSecret(ctx context.Context, userID uuid.UUID, webhookSecret sql.NullString) error
	UnregisterFCMToken(ctx context.Context, userID uuid.UUID, fcmToken string) error
	UpsertUpTransaction(ctx context.Context, arg UpsertUpTransactionParams) (bool, error)
	UpsertUser(ctx context.Context, email string) (FloatUser, error)
}

var _ Querier = (*Queries)(nil)
