// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rules.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createRule = `-- name: CreateRule :one
INSERT INTO float.rules (bucket_id, name, priority, description_contains, min_amount_cents, max_amount_cents, transaction_type, category_id, date_from, date_to, foreign_currency_code)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING rule_id, bucket_id, name, priority, description_contains, min_amount_cents, max_amount_cents, transaction_type, category_id, date_from, date_to, foreign_currency_code, created_at
`

type CreateRuleParams struct {
	BucketID            uuid.UUID
	Name                string
	Priority            int32
	DescriptionContains sql.NullString
	MinAmountCents      sql.NullInt64
	MaxAmountCents      sql.NullInt64
	TransactionType     sql.NullString
	CategoryID          sql.NullString
	DateFrom            sql.NullTime
	DateTo              sql.NullTime
	ForeignCurrencyCode sql.NullString
}

type CreateRuleRow struct {
	RuleID              uuid.UUID
	BucketID            uuid.UUID
	Name                string
	Priority            int32
	DescriptionContains sql.NullString
	MinAmountCents      sql.NullInt64
	MaxAmountCents      sql.NullInt64
	TransactionType     sql.NullString
	CategoryID          sql.NullString
	DateFrom            sql.NullTime
	DateTo              sql.NullTime
	ForeignCurrencyCode sql.NullString
	CreatedAt           time.Time
}

func (q *Queries) CreateRule(ctx context.Context, arg CreateRuleParams) (CreateRuleRow, error) {
	row := q.db.QueryRowContext(ctx, createRule,
		arg.BucketID,
		arg.Name,
		arg.Priority,
		arg.DescriptionContains,
		arg.MinAmountCents,
		arg.MaxAmountCents,
		arg.TransactionType,
		arg.CategoryID,
		arg.DateFrom,
		arg.DateTo,
		arg.ForeignCurrencyCode,
	)
	var i CreateRuleRow
	err := row.Scan(
		&i.RuleID,
		&i.BucketID,
		&i.Name,
		&i.Priority,
		&i.DescriptionContains,
		&i.MinAmountCents,
		&i.MaxAmountCents,
		&i.TransactionType,
		&i.CategoryID,
		&i.DateFrom,
		&i.DateTo,
		&i.ForeignCurrencyCode,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRule = `-- name: DeleteRule :exec
DELETE FROM float.rules r
USING float.buckets b
WHERE r.rule_id = $1 AND r.bucket_id = b.bucket_id AND b.user_id = $2
`

func (q *Queries) DeleteRule(ctx context.Context, ruleID uuid.UUID, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteRule, ruleID, userID)
	return err
}

const listRulesByBucket = `-- name: ListRulesByBucket :many
SELECT r.rule_id, r.bucket_id, r.name, r.priority,
       r.description_contains, r.min_amount_cents, r.max_amount_cents,
       r.transaction_type, r.category_id,
       r.date_from, r.date_to, r.foreign_currency_code,
       r.created_at,
       b.name AS bucket_name
FROM float.rules r
JOIN float.buckets b USING (bucket_id)
WHERE r.bucket_id = $1 AND b.user_id = $2
ORDER BY r.priority ASC, r.created_at ASC
`

type ListRulesByBucketRow struct {
	RuleID              uuid.UUID
	BucketID            uuid.UUID
	Name                string
	Priority            int32
	DescriptionContains sql.NullString
	MinAmountCents      sql.NullInt64
	MaxAmountCents      sql.NullInt64
	TransactionType     sql.NullString
	CategoryID          sql.NullString
	DateFrom            sql.NullTime
	DateTo              sql.NullTime
	ForeignCurrencyCode sql.NullString
	CreatedAt           time.Time
	BucketName          string
}

func (q *Queries) ListRulesByBucket(ctx context.Context, bucketID uuid.UUID, userID uuid.UUID) ([]ListRulesByBucketRow, error) {
	rows, err := q.db.QueryContext(ctx, listRulesByBucket, bucketID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRulesByBucketRow
	for rows.Next() {
		var i ListRulesByBucketRow
		if err := rows.Scan(
			&i.RuleID,
			&i.BucketID,
			&i.Name,
			&i.Priority,
			&i.DescriptionContains,
			&i.MinAmountCents,
			&i.MaxAmountCents,
			&i.TransactionType,
			&i.CategoryID,
			&i.DateFrom,
			&i.DateTo,
			&i.ForeignCurrencyCode,
			&i.CreatedAt,
			&i.BucketName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRulesForUser = `-- name: ListRulesForUser :many
SELECT r.rule_id, r.bucket_id, r.name, r.priority,
       r.description_contains, r.min_amount_cents, r.max_amount_cents,
       r.transaction_type, r.category_id,
       r.date_from, r.date_to, r.foreign_currency_code,
       r.created_at,
       b.name AS bucket_name
FROM float.rules r
JOIN float.buckets b USING (bucket_id)
WHERE b.user_id = $1
ORDER BY r.priority ASC, r.created_at ASC
`

type ListRulesForUserRow struct {
	RuleID              uuid.UUID
	BucketID            uuid.UUID
	Name                string
	Priority            int32
	DescriptionContains sql.NullString
	MinAmountCents      sql.NullInt64
	MaxAmountCents      sql.NullInt64
	TransactionType     sql.NullString
	CategoryID          sql.NullString
	DateFrom            sql.NullTime
	DateTo              sql.NullTime
	ForeignCurrencyCode sql.NullString
	CreatedAt           time.Time
	BucketName          string
}

func (q *Queries) ListRulesForUser(ctx context.Context, userID uuid.UUID) ([]ListRulesForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listRulesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRulesForUserRow
	for rows.Next() {
		var i ListRulesForUserRow
		if err := rows.Scan(
			&i.RuleID,
			&i.BucketID,
			&i.Name,
			&i.Priority,
			&i.DescriptionContains,
			&i.MinAmountCents,
			&i.MaxAmountCents,
			&i.TransactionType,
			&i.CategoryID,
			&i.DateFrom,
			&i.DateTo,
			&i.ForeignCurrencyCode,
			&i.CreatedAt,
			&i.BucketName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpTransactionsByBucketID = `-- name: ListUpTransactionsByBucketID :many
SELECT transaction_id, bucket_id, description, message, amount_cents, foreign_currency_code, foreign_amount_cents, created_at, transaction_type, raw_json, category_id FROM float.up_transactions WHERE bucket_id = $1
`

type ListUpTransactionsByBucketIDRow struct {
	TransactionID       uuid.UUID
	BucketID            uuid.UUID
	Description         string
	Message             string
	AmountCents         int64
	ForeignCurrencyCode sql.NullString
	ForeignAmountCents  sql.NullInt64
	CreatedAt           time.Time
	TransactionType     sql.NullString
	RawJson             json.RawMessage
	CategoryID          sql.NullString
}

func (q *Queries) ListUpTransactionsByBucketID(ctx context.Context, bucketID uuid.UUID) ([]ListUpTransactionsByBucketIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listUpTransactionsByBucketID, bucketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUpTransactionsByBucketIDRow
	for rows.Next() {
		var i ListUpTransactionsByBucketIDRow
		if err := rows.Scan(
			&i.TransactionID,
			&i.BucketID,
			&i.Description,
			&i.Message,
			&i.AmountCents,
			&i.ForeignCurrencyCode,
			&i.ForeignAmountCents,
			&i.CreatedAt,
			&i.TransactionType,
			&i.RawJson,
			&i.CategoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRule = `-- name: UpdateRule :one
UPDATE float.rules r
SET name                 = $2,
    priority             = $3,
    description_contains = $4,
    min_amount_cents     = $5,
    max_amount_cents     = $6,
    transaction_type     = $7,
    category_id          = $8,
    date_from            = $9,
    date_to              = $10,
    foreign_currency_code = $11
FROM float.buckets b
WHERE r.rule_id = $1 AND r.bucket_id = b.bucket_id AND b.user_id = $12
RETURNING r.rule_id, r.bucket_id, r.name, r.priority, r.description_contains, r.min_amount_cents, r.max_amount_cents, r.transaction_type, r.category_id, r.date_from, r.date_to, r.foreign_currency_code, r.created_at
`

type UpdateRuleParams struct {
	RuleID              uuid.UUID
	Name                string
	Priority            int32
	DescriptionContains sql.NullString
	MinAmountCents      sql.NullInt64
	MaxAmountCents      sql.NullInt64
	TransactionType     sql.NullString
	CategoryID          sql.NullString
	DateFrom            sql.NullTime
	DateTo              sql.NullTime
	ForeignCurrencyCode sql.NullString
	UserID              uuid.UUID
}

type UpdateRuleRow struct {
	RuleID              uuid.UUID
	BucketID            uuid.UUID
	Name                string
	Priority            int32
	DescriptionContains sql.NullString
	MinAmountCents      sql.NullInt64
	MaxAmountCents      sql.NullInt64
	TransactionType     sql.NullString
	CategoryID          sql.NullString
	DateFrom            sql.NullTime
	DateTo              sql.NullTime
	ForeignCurrencyCode sql.NullString
	CreatedAt           time.Time
}

func (q *Queries) UpdateRule(ctx context.Context, arg UpdateRuleParams) (UpdateRuleRow, error) {
	row := q.db.QueryRowContext(ctx, updateRule,
		arg.RuleID,
		arg.Name,
		arg.Priority,
		arg.DescriptionContains,
		arg.MinAmountCents,
		arg.MaxAmountCents,
		arg.TransactionType,
		arg.CategoryID,
		arg.DateFrom,
		arg.DateTo,
		arg.ForeignCurrencyCode,
		arg.UserID,
	)
	var i UpdateRuleRow
	err := row.Scan(
		&i.RuleID,
		&i.BucketID,
		&i.Name,
		&i.Priority,
		&i.DescriptionContains,
		&i.MinAmountCents,
		&i.MaxAmountCents,
		&i.TransactionType,
		&i.CategoryID,
		&i.DateFrom,
		&i.DateTo,
		&i.ForeignCurrencyCode,
		&i.CreatedAt,
	)
	return i, err
}
