// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const assignTransactionToBucket = `-- name: AssignTransactionToBucket :exec
UPDATE float.up_transactions
SET bucket_id = $2
WHERE transaction_id = $1
`

func (q *Queries) AssignTransactionToBucket(ctx context.Context, transactionID uuid.UUID, bucketID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, assignTransactionToBucket, transactionID, bucketID)
	return err
}

const deleteUpTransaction = `-- name: DeleteUpTransaction :exec
DELETE FROM float.up_transactions WHERE transaction_id = $1
`

func (q *Queries) DeleteUpTransaction(ctx context.Context, transactionID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUpTransaction, transactionID)
	return err
}

const getTransaction = `-- name: GetTransaction :one
SELECT l.transaction_id, l.bucket_id, l.description, l.message, l.amount_cents, l.display_amount, l.currency_code, l.created_at, l.is_transaction FROM float.bucket_ledger l
JOIN float.buckets b USING (bucket_id)
WHERE l.transaction_id = $1 AND b.user_id = $2
`

func (q *Queries) GetTransaction(ctx context.Context, transactionID uuid.UUID, userID uuid.UUID) (FloatBucketLedger, error) {
	row := q.db.QueryRowContext(ctx, getTransaction, transactionID, userID)
	var i FloatBucketLedger
	err := row.Scan(
		&i.TransactionID,
		&i.BucketID,
		&i.Description,
		&i.Message,
		&i.AmountCents,
		&i.DisplayAmount,
		&i.CurrencyCode,
		&i.CreatedAt,
		&i.IsTransaction,
	)
	return i, err
}

const listBucketTransactions = `-- name: ListBucketTransactions :many
SELECT transaction_id, bucket_id, description, message, amount_cents, display_amount, currency_code, created_at, is_transaction FROM float.bucket_ledger
WHERE bucket_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListBucketTransactions(ctx context.Context, bucketID uuid.UUID) ([]FloatBucketLedger, error) {
	rows, err := q.db.QueryContext(ctx, listBucketTransactions, bucketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FloatBucketLedger
	for rows.Next() {
		var i FloatBucketLedger
		if err := rows.Scan(
			&i.TransactionID,
			&i.BucketID,
			&i.Description,
			&i.Message,
			&i.AmountCents,
			&i.DisplayAmount,
			&i.CurrencyCode,
			&i.CreatedAt,
			&i.IsTransaction,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactions = `-- name: ListTransactions :many
SELECT l.transaction_id, l.bucket_id, l.description, l.message, l.amount_cents, l.display_amount, l.currency_code, l.created_at, l.is_transaction FROM float.bucket_ledger l
JOIN float.buckets b USING (bucket_id)
WHERE b.user_id = $1
ORDER BY l.created_at DESC
`

func (q *Queries) ListTransactions(ctx context.Context, userID uuid.UUID) ([]FloatBucketLedger, error) {
	rows, err := q.db.QueryContext(ctx, listTransactions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FloatBucketLedger
	for rows.Next() {
		var i FloatBucketLedger
		if err := rows.Scan(
			&i.TransactionID,
			&i.BucketID,
			&i.Description,
			&i.Message,
			&i.AmountCents,
			&i.DisplayAmount,
			&i.CurrencyCode,
			&i.CreatedAt,
			&i.IsTransaction,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUpTransaction = `-- name: UpsertUpTransaction :one
INSERT INTO float.up_transactions (
    transaction_id, bucket_id, description, message,
    amount_cents, display_amount, currency_code, created_at, transaction_type,
    raw_json, category_id
) VALUES (
    $1,
    (SELECT bucket_id FROM float.buckets WHERE user_id = $2 AND is_general = TRUE),
    $3, $4, $5, $6, $7, $8, $9, $10, $11
)
ON CONFLICT (transaction_id) DO UPDATE SET
    description = EXCLUDED.description,
    message = EXCLUDED.message,
    amount_cents = EXCLUDED.amount_cents,
    display_amount = EXCLUDED.display_amount,
    currency_code = EXCLUDED.currency_code,
    created_at = EXCLUDED.created_at,
    transaction_type = EXCLUDED.transaction_type,
    raw_json = EXCLUDED.raw_json,
    category_id = EXCLUDED.category_id
RETURNING (xmax = 0) AS inserted
`

type UpsertUpTransactionParams struct {
	TransactionID   uuid.UUID
	UserID          uuid.UUID
	Description     string
	Message         string
	AmountCents     int64
	DisplayAmount   string
	CurrencyCode    string
	CreatedAt       time.Time
	TransactionType sql.NullString
	RawJson         json.RawMessage
	CategoryID      sql.NullString
}

func (q *Queries) UpsertUpTransaction(ctx context.Context, arg UpsertUpTransactionParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, upsertUpTransaction,
		arg.TransactionID,
		arg.UserID,
		arg.Description,
		arg.Message,
		arg.AmountCents,
		arg.DisplayAmount,
		arg.CurrencyCode,
		arg.CreatedAt,
		arg.TransactionType,
		arg.RawJson,
		arg.CategoryID,
	)
	var inserted bool
	err := row.Scan(&inserted)
	return inserted, err
}
