// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transfers.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createTransfer = `-- name: CreateTransfer :one
INSERT INTO float.bucket_transfers (from_bucket_id, to_bucket_id, amount_cents, note)
VALUES ($1, $2, $3, $4)
RETURNING transfer_id, from_bucket_id, to_bucket_id, amount_cents, note, created_at
`

type CreateTransferParams struct {
	FromBucketID uuid.UUID
	ToBucketID   uuid.UUID
	AmountCents  int64
	Note         string
}

func (q *Queries) CreateTransfer(ctx context.Context, arg CreateTransferParams) (FloatBucketTransfer, error) {
	row := q.db.QueryRowContext(ctx, createTransfer,
		arg.FromBucketID,
		arg.ToBucketID,
		arg.AmountCents,
		arg.Note,
	)
	var i FloatBucketTransfer
	err := row.Scan(
		&i.TransferID,
		&i.FromBucketID,
		&i.ToBucketID,
		&i.AmountCents,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTransfer = `-- name: DeleteTransfer :execrows
DELETE FROM float.bucket_transfers t
USING float.buckets b
WHERE t.transfer_id = $1 AND t.from_bucket_id = b.bucket_id AND b.user_id = $2
`

func (q *Queries) DeleteTransfer(ctx context.Context, transferID uuid.UUID, userID uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTransfer, transferID, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listTransfers = `-- name: ListTransfers :many
SELECT
    t.transfer_id,
    t.from_bucket_id,
    fb.name AS from_bucket_name,
    t.to_bucket_id,
    tb.name AS to_bucket_name,
    t.amount_cents,
    t.note,
    t.created_at
FROM float.bucket_transfers t
JOIN float.buckets fb ON t.from_bucket_id = fb.bucket_id
JOIN float.buckets tb ON t.to_bucket_id = tb.bucket_id
WHERE fb.user_id = $1
ORDER BY t.created_at DESC
`

type ListTransfersRow struct {
	TransferID     uuid.UUID
	FromBucketID   uuid.UUID
	FromBucketName string
	ToBucketID     uuid.UUID
	ToBucketName   string
	AmountCents    int64
	Note           string
	CreatedAt      time.Time
}

func (q *Queries) ListTransfers(ctx context.Context, userID uuid.UUID) ([]ListTransfersRow, error) {
	rows, err := q.db.QueryContext(ctx, listTransfers, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransfersRow
	for rows.Next() {
		var i ListTransfersRow
		if err := rows.Scan(
			&i.TransferID,
			&i.FromBucketID,
			&i.FromBucketName,
			&i.ToBucketID,
			&i.ToBucketName,
			&i.AmountCents,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
