// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: trickles.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const deleteTrickle = `-- name: DeleteTrickle :execrows
DELETE FROM float.bucket_trickles t
USING float.buckets b
WHERE t.trickle_id = $1 AND t.to_bucket_id = b.bucket_id AND b.user_id = $2
`

func (q *Queries) DeleteTrickle(ctx context.Context, trickleID uuid.UUID, userID uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTrickle, trickleID, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getActiveTrickleByToBucketID = `-- name: GetActiveTrickleByToBucketID :one
SELECT t.trickle_id, t.from_bucket_id, t.to_bucket_id, t.amount_cents, t.description, t.period, t.start_date, t.end_date, t.created_at, tb.name AS to_bucket_name, fb.name AS from_bucket_name
FROM float.bucket_trickles t
JOIN float.buckets tb ON tb.bucket_id = t.to_bucket_id
JOIN float.buckets fb ON fb.bucket_id = t.from_bucket_id
WHERE t.to_bucket_id = $1 AND tb.user_id = $2
  AND (t.end_date IS NULL OR t.end_date >= CURRENT_DATE)
ORDER BY t.created_at DESC
LIMIT 1
`

type GetActiveTrickleByToBucketIDRow struct {
	TrickleID      uuid.UUID
	FromBucketID   uuid.UUID
	ToBucketID     uuid.UUID
	AmountCents    int64
	Description    string
	Period         string
	StartDate      time.Time
	EndDate        sql.NullTime
	CreatedAt      time.Time
	ToBucketName   string
	FromBucketName string
}

func (q *Queries) GetActiveTrickleByToBucketID(ctx context.Context, toBucketID uuid.UUID, userID uuid.UUID) (GetActiveTrickleByToBucketIDRow, error) {
	row := q.db.QueryRowContext(ctx, getActiveTrickleByToBucketID, toBucketID, userID)
	var i GetActiveTrickleByToBucketIDRow
	err := row.Scan(
		&i.TrickleID,
		&i.FromBucketID,
		&i.ToBucketID,
		&i.AmountCents,
		&i.Description,
		&i.Period,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.ToBucketName,
		&i.FromBucketName,
	)
	return i, err
}

const getTricklesByBucketID = `-- name: GetTricklesByBucketID :many
SELECT t.trickle_id, t.from_bucket_id, t.to_bucket_id, t.amount_cents, t.description, t.period, t.start_date, t.end_date, t.created_at, tb.name AS to_bucket_name, fb.name AS from_bucket_name
FROM float.bucket_trickles t
JOIN float.buckets tb ON tb.bucket_id = t.to_bucket_id
JOIN float.buckets fb ON fb.bucket_id = t.from_bucket_id
WHERE t.to_bucket_id = $1 OR t.from_bucket_id = $1
`

type GetTricklesByBucketIDRow struct {
	TrickleID      uuid.UUID
	FromBucketID   uuid.UUID
	ToBucketID     uuid.UUID
	AmountCents    int64
	Description    string
	Period         string
	StartDate      time.Time
	EndDate        sql.NullTime
	CreatedAt      time.Time
	ToBucketName   string
	FromBucketName string
}

func (q *Queries) GetTricklesByBucketID(ctx context.Context, toBucketID uuid.UUID) ([]GetTricklesByBucketIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getTricklesByBucketID, toBucketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTricklesByBucketIDRow
	for rows.Next() {
		var i GetTricklesByBucketIDRow
		if err := rows.Scan(
			&i.TrickleID,
			&i.FromBucketID,
			&i.ToBucketID,
			&i.AmountCents,
			&i.Description,
			&i.Period,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.ToBucketName,
			&i.FromBucketName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertTrickle = `-- name: InsertTrickle :one
INSERT INTO float.bucket_trickles (from_bucket_id, to_bucket_id, amount_cents, description, period, start_date, end_date)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING trickle_id, from_bucket_id, to_bucket_id, amount_cents, description, period, start_date, end_date, created_at
`

type InsertTrickleParams struct {
	FromBucketID uuid.UUID
	ToBucketID   uuid.UUID
	AmountCents  int64
	Description  string
	Period       string
	StartDate    time.Time
	EndDate      sql.NullTime
}

func (q *Queries) InsertTrickle(ctx context.Context, arg InsertTrickleParams) (FloatBucketTrickle, error) {
	row := q.db.QueryRowContext(ctx, insertTrickle,
		arg.FromBucketID,
		arg.ToBucketID,
		arg.AmountCents,
		arg.Description,
		arg.Period,
		arg.StartDate,
		arg.EndDate,
	)
	var i FloatBucketTrickle
	err := row.Scan(
		&i.TrickleID,
		&i.FromBucketID,
		&i.ToBucketID,
		&i.AmountCents,
		&i.Description,
		&i.Period,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
	)
	return i, err
}

const listTrickles = `-- name: ListTrickles :many
SELECT t.trickle_id, t.from_bucket_id, t.to_bucket_id, t.amount_cents, t.description, t.period, t.start_date, t.end_date, t.created_at, tb.name AS to_bucket_name, fb.name AS from_bucket_name
FROM float.bucket_trickles t
JOIN float.buckets tb ON tb.bucket_id = t.to_bucket_id
JOIN float.buckets fb ON fb.bucket_id = t.from_bucket_id
WHERE tb.user_id = $1
  AND tb.status = 'active'
  AND (t.end_date IS NULL OR t.end_date >= CURRENT_DATE)
ORDER BY t.created_at DESC
`

type ListTricklesRow struct {
	TrickleID      uuid.UUID
	FromBucketID   uuid.UUID
	ToBucketID     uuid.UUID
	AmountCents    int64
	Description    string
	Period         string
	StartDate      time.Time
	EndDate        sql.NullTime
	CreatedAt      time.Time
	ToBucketName   string
	FromBucketName string
}

func (q *Queries) ListTrickles(ctx context.Context, userID uuid.UUID) ([]ListTricklesRow, error) {
	rows, err := q.db.QueryContext(ctx, listTrickles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTricklesRow
	for rows.Next() {
		var i ListTricklesRow
		if err := rows.Scan(
			&i.TrickleID,
			&i.FromBucketID,
			&i.ToBucketID,
			&i.AmountCents,
			&i.Description,
			&i.Period,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.ToBucketName,
			&i.FromBucketName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTrickleEndDate = `-- name: SetTrickleEndDate :exec
UPDATE float.bucket_trickles t
SET end_date = $2
FROM float.buckets b
WHERE t.trickle_id = $1 AND t.to_bucket_id = b.bucket_id AND b.user_id = $3
`

func (q *Queries) SetTrickleEndDate(ctx context.Context, trickleID uuid.UUID, endDate sql.NullTime, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, setTrickleEndDate, trickleID, endDate, userID)
	return err
}
