// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT user_id, email, created_at FROM float.users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (FloatUser, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i FloatUser
	err := row.Scan(&i.UserID, &i.Email, &i.CreatedAt)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT user_id, email, created_at FROM float.users
WHERE user_id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, userID uuid.UUID) (FloatUser, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, userID)
	var i FloatUser
	err := row.Scan(&i.UserID, &i.Email, &i.CreatedAt)
	return i, err
}

const getUserToken = `-- name: GetUserToken :one
SELECT up_token FROM float.user_tokens
WHERE user_id = $1
`

func (q *Queries) GetUserToken(ctx context.Context, userID uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserToken, userID)
	var up_token string
	err := row.Scan(&up_token)
	return up_token, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO float.users (email)
VALUES ($1)
ON CONFLICT (email) DO UPDATE SET email = EXCLUDED.email
RETURNING user_id, email, created_at
`

func (q *Queries) UpsertUser(ctx context.Context, email string) (FloatUser, error) {
	row := q.db.QueryRowContext(ctx, upsertUser, email)
	var i FloatUser
	err := row.Scan(&i.UserID, &i.Email, &i.CreatedAt)
	return i, err
}

const upsertUserToken = `-- name: UpsertUserToken :exec
INSERT INTO float.user_tokens (user_id, up_token)
VALUES ($1, $2)
ON CONFLICT (user_id) DO UPDATE SET up_token = EXCLUDED.up_token
`

func (q *Queries) UpsertUserToken(ctx context.Context, userID uuid.UUID, upToken string) error {
	_, err := q.db.ExecContext(ctx, upsertUserToken, userID, upToken)
	return err
}
