// Package mastercard provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package mastercard

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// ServerUrlProductionServer defines the Server URL for Production server
const ServerUrlProductionServer = "https://api.mastercard.com/enhanced/settlement/currencyrate/subscribed"

// ServerUrlSandboxServer defines the Server URL for Sandbox server
const ServerUrlSandboxServer = "https://sandbox.api.mastercard.com/enhanced/settlement/currencyrate/subscribed"

// ECBConversionObject defines model for ECBConversionObject.
type ECBConversionObject struct {
	// EcbReferenceRate Euro foreign exchange reference rates issued by the European Central Bank (ECB). When neither the transaction currency nor the cardholder billing currency is equal to Euro, a calculated reference rate is derived from the two ECB rates
	EcbReferenceRate *float32 `json:"ecbReferenceRate,omitempty"`

	// EcbReferenceRateDate Date of reference rates issued by the European Central Bank (ECB).
	EcbReferenceRateDate *string `json:"ecbReferenceRateDate,omitempty"`

	// Message User friendly message (if applicable)
	Message *string `json:"message,omitempty"`

	// ReasonCode User friendly reason code (if applicable)
	ReasonCode *string `json:"reasonCode,omitempty"`
}

// EcbError defines model for EcbError.
type EcbError struct {
	// Description Short description of the ReasonCode field.
	Description *string `json:"Description,omitempty"`

	// Details Where appropriate, indicates detailed information about data received and calculated during request processing, to help the user with diagnosing errors.
	Details *string `json:"Details,omitempty"`

	// ReasonCode A unique constant identifying the error case encountered during transaction processing. For example, INVALID_SIGNATURE is used when the request signature does not match the expected one.
	ReasonCode *string `json:"ReasonCode,omitempty"`

	// Recoverable Indicates whether this error will always be returned for this request, or retrying could change the outcome. For example, if the request contains an invalid   signature, retrying will never result in a success. However, if the error is related to some unexpected timeout with the service, retrying the call could result in a successful response.
	Recoverable *bool `json:"Recoverable,omitempty"`

	// Source The name of the application that generated this error
	Source *string `json:"Source,omitempty"`
}

// EcbMcRateIssued defines model for EcbMcRateIssued.
type EcbMcRateIssued struct {
	// Message User friendly message (if applicable)
	Message *string `json:"message,omitempty"`

	// ReasonCode User friendly reason code (if applicable)
	ReasonCode *string `json:"reasonCode,omitempty"`

	// Status Provides rate status as yes/No
	Status *string `json:"status,omitempty"`
}

// EnhancedCurrency defines model for EnhancedCurrency.
type EnhancedCurrency struct {
	// AlphaCd The currency code for the currency
	AlphaCd *string `json:"alphaCd,omitempty"`

	// CurrName The full name of the currency
	CurrName *string `json:"currName,omitempty"`
}

// EnhancedCurrencyConversionData defines model for EnhancedCurrencyConversionData.
type EnhancedCurrencyConversionData struct {
	// BankFeeFixed Fixed bank fee as provided in the API request
	BankFeeFixed *float32 `json:"bankFeeFixed,omitempty"`

	// BankFeePct Percentage bank fee as provided in the API request
	BankFeePct *float32 `json:"bankFeePct,omitempty"`

	// CrdhldBillCurr Cardholder billing currency as provided in the API request
	CrdhldBillCurr *string              `json:"crdhldBillCurr,omitempty"`
	Ecb            *ECBConversionObject `json:"ecb,omitempty"`

	// EffectiveConversionRate Calculated effective exchange rate for the requested currency pair including all issuer-to-cardholder fees. This is calculated by dividing cardholder billing amount including all fees divided by the transaction amount (crdhldBillAmtInclAllFees / transAmount)
	EffectiveConversionRate *float32                    `json:"effectiveConversionRate,omitempty"`
	Mastercard              *MastercardConversionObject `json:"mastercard,omitempty"`

	// PctDifferenceMastercardExclAllFeesAndEcb Calculated percentage difference between Mastercard Conversion Rate excluding all issuer-to-cardholder fees for the selected currency pair and the ECB Reference Rate
	PctDifferenceMastercardExclAllFeesAndEcb *float32 `json:"pctDifferenceMastercardExclAllFeesAndEcb,omitempty"`

	// PctDifferenceMastercardInclAllFeesAndEcb Calculated percentage difference between Mastercard Conversion Rate Including all issuer-to-cardholder fees (fixed and percentage) for the selected currency pair and the ECB Reference Rate ([effectiveConversionRate/ecbReferenceRateDate]-1*100)
	PctDifferenceMastercardInclAllFeesAndEcb *float32 `json:"pctDifferenceMastercardInclAllFeesAndEcb,omitempty"`

	// RateDate The date of the requested rates
	RateDate *string `json:"rateDate,omitempty"`

	// TransAmt Amount in transaction currency as provided in the API request
	TransAmt *float32 `json:"transAmt,omitempty"`

	// TransCurr Currency of the transaction as provided in the API request
	TransCurr *string `json:"transCurr,omitempty"`
}

// EnhancedCurrencyConversionWrapper defines model for EnhancedCurrencyConversionWrapper.
type EnhancedCurrencyConversionWrapper struct {
	Data *EnhancedCurrencyConversionData `json:"data,omitempty"`

	// Description The description of the API being called
	Description *string `json:"description,omitempty"`

	// Name The name of the service being requested
	Name *string `json:"name,omitempty"`

	// RequestDate The date and time the API is being called in GMT
	RequestDate *string `json:"requestDate,omitempty"`
}

// EnhancedEcbCurrencies defines model for EnhancedEcbCurrencies.
type EnhancedEcbCurrencies struct {
	// Currencies List of ECB Currencies
	Currencies *[]EnhancedCurrency `json:"currencies,omitempty"`

	// CurrencyCount Number of ECB Currencies
	CurrencyCount *int32 `json:"currencyCount,omitempty"`
}

// EnhancedEcbCurrencyWrapper defines model for EnhancedEcbCurrencyWrapper.
type EnhancedEcbCurrencyWrapper struct {
	Data *EnhancedEcbCurrencies `json:"data,omitempty"`

	// Description The description of the API being called
	Description *string `json:"description,omitempty"`

	// Name The name of the service being requested
	Name *string `json:"name,omitempty"`

	// RequestDate The date and time the API is being called in GMT
	RequestDate *string `json:"requestDate,omitempty"`
}

// EnhancedMastercardCurrencies defines model for EnhancedMastercardCurrencies.
type EnhancedMastercardCurrencies struct {
	// Currencies List of Mastercard Currencies
	Currencies *[]EnhancedCurrency `json:"currencies,omitempty"`

	// CurrencyCount Number of Mastercard Currencies
	CurrencyCount *int32 `json:"currencyCount,omitempty"`
}

// EnhancedMastercardCurrencyWrapper defines model for EnhancedMastercardCurrencyWrapper.
type EnhancedMastercardCurrencyWrapper struct {
	Data *EnhancedMastercardCurrencies `json:"data,omitempty"`

	// Description The description of the API being called
	Description *string `json:"description,omitempty"`

	// Name The name of the service being requested
	Name *string `json:"name,omitempty"`

	// RequestDate The date and time the API is being called in GMT
	RequestDate *string `json:"requestDate,omitempty"`
}

// EnhancedSettlementRateIssued defines model for EnhancedSettlementRateIssued.
type EnhancedSettlementRateIssued struct {
	EcbRateIssued        *EcbMcRateIssued `json:"ecbRateIssued,omitempty"`
	MastercardRateIssued *EcbMcRateIssued `json:"mastercardRateIssued,omitempty"`

	// RateDate The date of the requested rates
	RateDate *string `json:"rateDate,omitempty"`
}

// EnhancedSettlementRateIssuedWrapper defines model for EnhancedSettlementRateIssuedWrapper.
type EnhancedSettlementRateIssuedWrapper struct {
	Data *EnhancedSettlementRateIssued `json:"data,omitempty"`

	// Description The description of the API being called
	Description *string `json:"description,omitempty"`

	// Name The name of the service being requested
	Name *string `json:"name,omitempty"`

	// RequestDate The date and time the API is being called in GMT
	RequestDate *string `json:"requestDate,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Errors Errors `json:"Errors"`
}

// Errors defines model for Errors.
type Errors struct {
	// Error if an errorhas occurred
	Error []EcbError `json:"Error"`
}

// MastercardConversionObject defines model for MastercardConversionObject.
type MastercardConversionObject struct {
	// CrdhldBillAmtExclAllFees Cardholder billing amount calculated by using the Mastercard conversion rate, excluding any applicable issuer-to-cardholder fees
	CrdhldBillAmtExclAllFees *float32 `json:"crdhldBillAmtExclAllFees,omitempty"`

	// CrdhldBillAmtInclAllFees Cardholder Billing Amount as calculated by applying the Mastercard Conversion Rate, including any applicable issuer-to-cardholder fees (percentage and fixed)
	CrdhldBillAmtInclAllFees *float32 `json:"crdhldBillAmtInclAllFees,omitempty"`

	// MastercardConvRateExclAllFees Mastercard exchange rate for the requested currency pair excluding any issuer-to-cardholder fees
	MastercardConvRateExclAllFees *float32 `json:"mastercardConvRateExclAllFees,omitempty"`

	// MastercardConvRateInclPctFee Mastercard exchange rate for the requested currency pair including issuer-to-cardholder percentage rate fee as provided by the issuer in the API call
	MastercardConvRateInclPctFee *float32 `json:"mastercardConvRateInclPctFee,omitempty"`

	// MastercardFxRateDate Date of Mastercard issued conversion rates. The date can differ to the requested rate date if no new rates are published for the requested date or if the user requests for a historical date
	MastercardFxRateDate *string `json:"mastercardFxRateDate,omitempty"`

	// Message User friendly message (if applicable)
	Message *string `json:"message,omitempty"`

	// ReasonCode User friendly reason code (if applicable)
	ReasonCode *string `json:"reasonCode,omitempty"`
}

// IsEcbMcRateIssuedUsingGETParams defines parameters for IsEcbMcRateIssuedUsingGET.
type IsEcbMcRateIssuedUsingGETParams struct {
	// RequestDate Rate issued date (YYYY-mm-dd)
	RequestDate *string `form:"request_date,omitempty" json:"request_date,omitempty"`
}

// GetEnhancedConversionDetailsUsingGETParams defines parameters for GetEnhancedConversionDetailsUsingGET.
type GetEnhancedConversionDetailsUsingGETParams struct {
	// RateDate Date of the requested FX rates
	RateDate string `form:"rate_date" json:"rate_date"`

	// TransCurr Currency of the transaction
	TransCurr string `form:"trans_curr" json:"trans_curr"`

	// TransAmt Amount in the transaction currency
	TransAmt float32 `form:"trans_amt" json:"trans_amt"`

	// CrdhldBillCurr Cardholder billing currency
	CrdhldBillCurr string `form:"crdhld_bill_curr" json:"crdhld_bill_curr"`

	// BankFeePct Percentage mark-up/fee (if applicable) an issuer would assess a cardholder on the cross-border/cross-currency transaction
	BankFeePct *float32 `form:"bank_fee_pct,omitempty" json:"bank_fee_pct,omitempty"`

	// BankFeeFixed Fixed mark-up/fee (if applicable) an issuer would assess a cardholder on the cross-border/cross-currency transaction (amount in cardholder billing currency)
	BankFeeFixed *float32 `form:"bank_fee_fixed,omitempty" json:"bank_fee_fixed,omitempty"`
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetEcbCurrenciesListUsingGET request
	GetEcbCurrenciesListUsingGET(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetEnhancedMCCurrencyDataUsingGET request
	GetEnhancedMCCurrencyDataUsingGET(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// IsEcbMcRateIssuedUsingGET request
	IsEcbMcRateIssuedUsingGET(ctx context.Context, params *IsEcbMcRateIssuedUsingGETParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetEnhancedConversionDetailsUsingGET request
	GetEnhancedConversionDetailsUsingGET(ctx context.Context, params *GetEnhancedConversionDetailsUsingGETParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetEcbCurrenciesListUsingGET(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetEcbCurrenciesListUsingGETRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetEnhancedMCCurrencyDataUsingGET(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetEnhancedMCCurrencyDataUsingGETRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) IsEcbMcRateIssuedUsingGET(ctx context.Context, params *IsEcbMcRateIssuedUsingGETParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewIsEcbMcRateIssuedUsingGETRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetEnhancedConversionDetailsUsingGET(ctx context.Context, params *GetEnhancedConversionDetailsUsingGETParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetEnhancedConversionDetailsUsingGETRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetEcbCurrenciesListUsingGETRequest generates requests for GetEcbCurrenciesListUsingGET
func NewGetEcbCurrenciesListUsingGETRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/ecb-currencies")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetEnhancedMCCurrencyDataUsingGETRequest generates requests for GetEnhancedMCCurrencyDataUsingGET
func NewGetEnhancedMCCurrencyDataUsingGETRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/mc-currencies")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewIsEcbMcRateIssuedUsingGETRequest generates requests for IsEcbMcRateIssuedUsingGET
func NewIsEcbMcRateIssuedUsingGETRequest(server string, params *IsEcbMcRateIssuedUsingGETParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/rate-statuses")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.RequestDate != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "request_date", *params.RequestDate, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetEnhancedConversionDetailsUsingGETRequest generates requests for GetEnhancedConversionDetailsUsingGET
func NewGetEnhancedConversionDetailsUsingGETRequest(server string, params *GetEnhancedConversionDetailsUsingGETParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/summary-rates")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "rate_date", params.RateDate, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "trans_curr", params.TransCurr, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "trans_amt", params.TransAmt, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "number", Format: ""}); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "crdhld_bill_curr", params.CrdhldBillCurr, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if params.BankFeePct != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "bank_fee_pct", *params.BankFeePct, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "number", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.BankFeeFixed != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "bank_fee_fixed", *params.BankFeeFixed, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "number", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetEcbCurrenciesListUsingGETWithResponse request
	GetEcbCurrenciesListUsingGETWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetEcbCurrenciesListUsingGETResponse, error)

	// GetEnhancedMCCurrencyDataUsingGETWithResponse request
	GetEnhancedMCCurrencyDataUsingGETWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetEnhancedMCCurrencyDataUsingGETResponse, error)

	// IsEcbMcRateIssuedUsingGETWithResponse request
	IsEcbMcRateIssuedUsingGETWithResponse(ctx context.Context, params *IsEcbMcRateIssuedUsingGETParams, reqEditors ...RequestEditorFn) (*IsEcbMcRateIssuedUsingGETResponse, error)

	// GetEnhancedConversionDetailsUsingGETWithResponse request
	GetEnhancedConversionDetailsUsingGETWithResponse(ctx context.Context, params *GetEnhancedConversionDetailsUsingGETParams, reqEditors ...RequestEditorFn) (*GetEnhancedConversionDetailsUsingGETResponse, error)
}

type GetEcbCurrenciesListUsingGETResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EnhancedEcbCurrencyWrapper
	JSON401      *ErrorResponse
	JSON404      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetEcbCurrenciesListUsingGETResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetEcbCurrenciesListUsingGETResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetEnhancedMCCurrencyDataUsingGETResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EnhancedMastercardCurrencyWrapper
	JSON401      *ErrorResponse
	JSON404      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetEnhancedMCCurrencyDataUsingGETResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetEnhancedMCCurrencyDataUsingGETResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type IsEcbMcRateIssuedUsingGETResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EnhancedSettlementRateIssuedWrapper
	JSON400      *ErrorResponse
	JSON401      *ErrorResponse
	JSON403      *ErrorResponse
	JSON404      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r IsEcbMcRateIssuedUsingGETResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r IsEcbMcRateIssuedUsingGETResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetEnhancedConversionDetailsUsingGETResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EnhancedCurrencyConversionWrapper
	JSON400      *ErrorResponse
	JSON401      *ErrorResponse
	JSON403      *ErrorResponse
	JSON404      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetEnhancedConversionDetailsUsingGETResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetEnhancedConversionDetailsUsingGETResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetEcbCurrenciesListUsingGETWithResponse request returning *GetEcbCurrenciesListUsingGETResponse
func (c *ClientWithResponses) GetEcbCurrenciesListUsingGETWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetEcbCurrenciesListUsingGETResponse, error) {
	rsp, err := c.GetEcbCurrenciesListUsingGET(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetEcbCurrenciesListUsingGETResponse(rsp)
}

// GetEnhancedMCCurrencyDataUsingGETWithResponse request returning *GetEnhancedMCCurrencyDataUsingGETResponse
func (c *ClientWithResponses) GetEnhancedMCCurrencyDataUsingGETWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetEnhancedMCCurrencyDataUsingGETResponse, error) {
	rsp, err := c.GetEnhancedMCCurrencyDataUsingGET(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetEnhancedMCCurrencyDataUsingGETResponse(rsp)
}

// IsEcbMcRateIssuedUsingGETWithResponse request returning *IsEcbMcRateIssuedUsingGETResponse
func (c *ClientWithResponses) IsEcbMcRateIssuedUsingGETWithResponse(ctx context.Context, params *IsEcbMcRateIssuedUsingGETParams, reqEditors ...RequestEditorFn) (*IsEcbMcRateIssuedUsingGETResponse, error) {
	rsp, err := c.IsEcbMcRateIssuedUsingGET(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseIsEcbMcRateIssuedUsingGETResponse(rsp)
}

// GetEnhancedConversionDetailsUsingGETWithResponse request returning *GetEnhancedConversionDetailsUsingGETResponse
func (c *ClientWithResponses) GetEnhancedConversionDetailsUsingGETWithResponse(ctx context.Context, params *GetEnhancedConversionDetailsUsingGETParams, reqEditors ...RequestEditorFn) (*GetEnhancedConversionDetailsUsingGETResponse, error) {
	rsp, err := c.GetEnhancedConversionDetailsUsingGET(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetEnhancedConversionDetailsUsingGETResponse(rsp)
}

// ParseGetEcbCurrenciesListUsingGETResponse parses an HTTP response from a GetEcbCurrenciesListUsingGETWithResponse call
func ParseGetEcbCurrenciesListUsingGETResponse(rsp *http.Response) (*GetEcbCurrenciesListUsingGETResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetEcbCurrenciesListUsingGETResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EnhancedEcbCurrencyWrapper
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseGetEnhancedMCCurrencyDataUsingGETResponse parses an HTTP response from a GetEnhancedMCCurrencyDataUsingGETWithResponse call
func ParseGetEnhancedMCCurrencyDataUsingGETResponse(rsp *http.Response) (*GetEnhancedMCCurrencyDataUsingGETResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetEnhancedMCCurrencyDataUsingGETResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EnhancedMastercardCurrencyWrapper
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseIsEcbMcRateIssuedUsingGETResponse parses an HTTP response from a IsEcbMcRateIssuedUsingGETWithResponse call
func ParseIsEcbMcRateIssuedUsingGETResponse(rsp *http.Response) (*IsEcbMcRateIssuedUsingGETResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &IsEcbMcRateIssuedUsingGETResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EnhancedSettlementRateIssuedWrapper
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseGetEnhancedConversionDetailsUsingGETResponse parses an HTTP response from a GetEnhancedConversionDetailsUsingGETWithResponse call
func ParseGetEnhancedConversionDetailsUsingGETResponse(rsp *http.Response) (*GetEnhancedConversionDetailsUsingGETResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetEnhancedConversionDetailsUsingGETResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EnhancedCurrencyConversionWrapper
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}
