name: Automerge

on:
  pull_request:
  pull_request_target:
    types: [labeled]
  issue_comment:
    types: [created]

jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      checks: read
    if: |
      (github.event_name == 'pull_request' && (github.actor == 'dependabot[bot]' ||  github.actor == 'dbut2[bot]')) ||
      (github.event_name == 'pull_request_target' && github.actor == 'dbut2' && github.event.label.name == 'automerge') ||
      (github.event_name == 'issue_comment' && github.event.issue.pull_request && github.actor == 'dbut2' && contains(github.event.comment.body, '/automerge'))
    steps:
      - name: Required Checks
        uses: RoryQ/required-checks@v1.2.1
        with:
          required_workflow_patterns: |
            - Build Check
            - Docker Compose
            - Go Generate
            - Go Mod Tidy
            - Go Test
            - Screenshots
            - golangci-lint
          token: ${{ secrets.GITHUB_TOKEN }}
          initial_delay_seconds: 0
          poll_frequency_seconds: 10
          missing_required_retry_count: 10

      - name: Generate token
        id: token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.DBUT2_APP_ID }}
          private-key: ${{ secrets.DBUT2_APP_PRIVATE_KEY }}

      - name: Enable auto-merge
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 12
          retry_wait_seconds: 10
          command: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url || github.event.issue.html_url }}
          GH_TOKEN: ${{ steps.token.outputs.token }}
