name: Quality Checks

on:
  pull_request:
  merge_group:

permissions:
  contents: read

jobs:
  quality:
    uses: dbut2/x/.github/workflows/quality-go.yaml@main

  docker:
    uses: dbut2/x/.github/workflows/quality-docker.yaml@main
